name = "katalina-site"
main = "src/worker.ts"
compatibility_date = "2026-04-27"

[assets]
directory = "./out"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "katalinalondono.com"
custom_domain = true

[[routes]]
pattern = "www.katalinalondono.com"
custom_domain = true
